export const SOURCES = [
  { id: "acaniza", name: "A Cañiza" },
  { id: "acoruna", name: "A Coruña" },
  { id: "allariz", name: "Allariz" },
  { id: "apobra", name: "A Pobra" },
  { id: "asneves", name: "As Neves" },
  { id: "baiona", name: "Baiona" },
  { id: "boiro", name: "Boiro" },
  { id: "catoira", name: "Catoira" },
  { id: "celanova", name: "Celanova" },
  { id: "chaves", name: "Chaves" },
  { id: "cm-melgaco", name: "Melgaço" },
  { id: "cm-valenca", name: "Valença" },
  { id: "covelo", name: "Covelo" },
  { id: "crecente", name: "Crecente" },
  { id: "cualedro", name: "Cualedro" },
  { id: "laza", name: "Laza" },
  { id: "lousame", name: "Lousame" },
  { id: "lugo", name: "Lugo" },
  { id: "moncao", name: "Monçao" },
  { id: "mondariz", name: "Mondariz" },
  { id: "mondarizbalneario", name: "Mondariz Balneario" },
  { id: "monterrei", name: "Monterrei" },
  { id: "mos", name: "Mos" },
  { id: "noia", name: "Noia" },
  { id: "oimbra", name: "Oimbra" },
  { id: "oporrino", name: "O Porriño" },
  { id: "ourense", name: "Ourense" },
  { id: "outes", name: "Outes" },
  { id: "padron", name: "Padrón" },
  { id: "ponteareas", name: "Ponteareas" },
  { id: "portodoson", name: "Porto do Son" },
  { id: "redondela", name: "Redondela" },
  { id: "rianxo", name: "Rianxo" },
  { id: "ribeira", name: "Ribeira" },
  { id: "salceda", name: "Salceda" },
  { id: "salvaterra", name: "Salvaterra de Miño" },
  { id: "santiago", name: "Santiago de Compostela" },
  { id: "tui", name: "Tui" },
  { id: "verin", name: "Verin" },
  { id: "vigo", name: "Vigo" },
  { id: "xinzodelimia", name: "Xinzo de limia" },
  { id: "xunta", name: "Xunta de Galicia" },
] as const;

export const sourcesWithHtmlContent = [
  "allariz",
  "apobra",
  "asneves",
  "baiona",
  "catoira",
  "cm-melgaco",
  "cm-valenca",
  "moncao",
  "mondariz",
  "mondarizbalneario",
  "monterrei",
  "mos",
  "noia",
  "ponteareas",
  "redondela",
  "rianxo",
  "salceda",
  "verin",
];

export const PAGE_SIZE = 18;
