name: Run News Scrapper

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  run-scripts:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps

      - name: Run cron script
        run: npm run cron

      - name: Run files script
        run: npm run files

      - name: Generate frontend
        run: npm run build

      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Commit changes
        run: |
          git config user.name jesusgm
          git config user.email jesusalxen@gmail.com
          git add docs packages/files/index.json packages/files/list.json
          git status
          git commit -m "[bot] Update news"
          git push origin main
